import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :scheduling, SchedulingWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :scheduling, SchedulingWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # The readiness/liveness probe connects to the pod IP over plain HTTP,
      # so it matches neither excluded host and got a 301 to https instead of
      # the health check's answer. Kubernetes counts 3xx as success, so the
      # pod stayed up and nothing looked broken — it just logged a redirect
      # every few seconds, which buries anything worth reading. The endpoint
      # returns no data and requires no auth, so there is nothing to protect
      # by upgrading it.
      paths: ["/api/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
