defmodule Scheduling.Repo.Migrations.CreateIdempotencyKeys do
  @moduledoc """
  Lets an external caller retry a write without performing it twice.

  A check-in bridge that times out waiting for `POST /queue_entries` has no way
  to know whether the patient was signed in. Retrying risks two queue entries
  for one arrival; not retrying risks none. Both are wrong in front of a
  waiting room, so the caller is given a third option: repeat the request with
  the same `Idempotency-Key` and get the *original* response back.

  Returning the original response — not merely "already done" — is what makes
  it useful, because the caller still needs the id of the thing that was
  created.

  `(caller, key)` is unique rather than `key` alone: keys are generated by
  callers, and two services picking the same UUID must not collide. It is also
  what stops one caller replaying another's response by guessing a key.

  `request_fingerprint` catches the same key being reused for a *different*
  request. Without it a caller who recycles a key silently receives the wrong
  cached response, which is worse than an error.
  """
  use Ecto.Migration

  def change do
    create table(:idempotency_keys) do
      add :caller, :string, null: false
      add :key, :string, null: false
      add :request_fingerprint, :string, null: false

      # Null until the request finishes. A row with no response is a claim: it
      # says somebody is mid-flight, which is how two concurrent retries are
      # told apart from one retry of a finished request.
      add :response_status, :integer
      add :response_body, :text
      add :response_content_type, :string

      timestamps(type: :utc_datetime_usec)
    end

    create unique_index(:idempotency_keys, [:caller, :key])

    # The sweeper deletes by age; without this it table-scans a table whose
    # whole purpose is to be written to on every retried write.
    create index(:idempotency_keys, [:inserted_at])
  end
end
